name: docker_build_push

on:
  push:
    tags:
      - 'v*'  # This will trigger the action for tags that start with 'v'

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # checks the code in the repository

      - name: Log in to DockerHub
        uses: docker/login-action@v3 # uses the username and token secrets to login to dockerhub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: recycleddirt/francis-ceg3120
          tags: |
            latest
            type=semver,pattern={{version}} # This will give you just the tag name (e.g., v1.2.3)
            type=semver,pattern={{.Major}} # This extracts the major version (e.g., v1)
            type=semver,pattern={{.Major}}.{{.Minor}} # This extracts the major and minor version (e.g., v1.2)

      - name: Debug Tags
        run: echo "Generated tags: ${{ steps.meta.outputs.tags }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.10.0 # uses other action
        with:
          context: Project4
          push: true
          tags: ${{ steps.meta.outputs.tags }} # Uses the tags generated by the metadata action
